# Generated by Django 2.2.15 on 2020-08-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='Education',
            field=models.CharField(default='SOME STRING', max_length=140000),
        ),
        migrations.AddField(
            model_name='cv',
            name='Experience',
            field=models.CharField(default='SOME STRING', max_length=100000),
        ),
        migrations.AddField(
            model_name='cv',
            name='Introduction',
            field=models.CharField(default='SOME STRING', max_length=15000),
        ),
        migrations.AddField(
            model_name='cv',
            name='Qualifications',
            field=models.CharField(default='SOME STRING', max_length=140000),
        ),
        migrations.AddField(
            model_name='cv',
            name='address',
            field=models.CharField(default='SOME STRING', max_length=256),
        ),
        migrations.AddField(
            model_name='cv',
            name='contact',
            field=models.CharField(default='SOME STRING', max_length=300),
        ),
        migrations.AddField(
            model_name='cv',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
        migrations.AlterField(
            model_name='cv',
            name='text',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
