# Generated by Django 2.2.15 on 2020-08-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200830_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='Education',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
        migrations.AlterField(
            model_name='cv',
            name='Experience',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
        migrations.AlterField(
            model_name='cv',
            name='Introduction',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
        migrations.AlterField(
            model_name='cv',
            name='Qualifications',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cv',
            name='address',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
        migrations.AlterField(
            model_name='cv',
            name='contact',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
        migrations.AlterField(
            model_name='cv',
            name='text',
            field=models.TextField(),
        ),
    ]
