# Generated by Django 2.2.15 on 2020-08-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200830_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='Education',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cv',
            name='Experience',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cv',
            name='Introduction',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cv',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cv',
            name='contact',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cv',
            name='name',
            field=models.CharField(default='Name', max_length=140),
        ),
        migrations.AlterField(
            model_name='cv',
            name='text',
            field=models.CharField(default='CV purpose', max_length=200),
        ),
    ]
